### ISSUE TITLE
LXC creation - not all storage types recognised/available

### ISSUE THREAD

**Issue by krikey** [blesta/module-proxmox#23]
# Describe

On my Proxmox server, I have 2 storage types; "local" which is a Directory storage type  and "local-lvm" which is LVM-Thin storage type but only "local" is shown in the product setup.

# Environment

Blesta Version: Blesta 5.6.1
Proxmox Version: 7.3-6
OS Version: Ubuntu 18.04
PHP Version: 7.4.33

**Comment by JReissmueller** [comment]
Just to confirm, this refers to the "Storage Name" field which is where the VMs are stored, and not the CT Template Storage, correct?

**Comment by TeYroXOfficial** [comment]
Could you please attach logs from module? Does both storages are available on "left" side?
I tested latest module on few nodes and wasn't able to reproduce your issue.

**Comment by JReissmueller** [comment]
It looks like the module is incorrectly filtering the Storage Name option to only show storage options that support the vztmpl content type.  I believe what we want to filter on is the "images" content type for KVM and the "rootdir" content type for LXC.  I'll make an update.
