### ISSUE TITLE
KVM package creation fails - Please enter a valid default template

### ISSUE THREAD

**Issue by krikey** [blesta/module-proxmox#24]
# Describe

When setting up a new package to support KVMs, I'm only presented with a "storage name" field which can be selected, but there is no field asking for a Default Template.

However when submitting the package I get the following errors:

```
Please enter a valid default template.

Please enter a valid storage.
```

# Environment

Blesta Version: Blesta 5.6.1
Proxmox Version: 7.3-6
OS Version: Ubuntu 18.04
PHP Version: 7.4.33

**Comment by JReissmueller** [comment]
Updated and resolved. Please try with the new code :)
