### ISSUE TITLE
Request: Password(s) are visible in plain text in the module setup

### ISSUE THREAD

**Issue by krikey** [blesta/module-proxmox#28]
Whilst the functionality seems to be working fine, I think it would be good practice to hide the password contents in the password field(s)

# Where

Settings > Company > Modules > Proxmox > Manage > Edit

![image](https://user-images.githubusercontent.com/87768441/228776585-078c9d94-7c69-425d-8714-a1d027a17aba.png)

**Comment by JReissmueller** [comment]
Resolved by #38
