### ISSUE TITLE
Error Upon KVM creation

### ISSUE THREAD

**Issue by joeymk2000** [blesta/module-proxmox#6]
Hello,

I am getting this error when adding a VM to a client (creating one for them)

`An internal error occurred and the client account could not be created.`

this is what the logs are saying:

INPUT: `MASKED-IP|client-checkexists
a:1:{s:6:"userid";s:7:"vmuser1";}`
OUTPUT: `MASKED-IP
{"data":null}`
INPUT: `51.89.173.174|client-create
a:5:MASKED-IP{s:6:"userid";s:7:"vmuser1";s:8:"password";s:3:"***";s:5:"email";s:16:"MASKED-USER-EMAIL";s:9:"firstname";s:4:"test";s:8:"lastname";s:4:"test";}`
OUTPUT: `MASKED-IP
{"data":null}`
INPUT: `MASKED-IP|client-checkexists
a:1:{s:6:"userid";s:7:"vmuser1";}`
OUTPUT: `MASKED-IP
{"data":null}`

**Comment by joeymk2000** [comment]
PS: I do get this message on the proxmox node: `successful auth for user 'apiuser@pve'`

**Comment by tysonphillips** [comment]
Your log indicates the Proxmox server is sending back an invalid response (i.e. nothing), or there is no response. You should check your Proxmox API credentials to ensure they're valid, that your Blesta server can communicate with the Proxmox server (e.g. ports are open), etc.

**Comment by joeymk2000** [comment]
I currently use another panel to manage proxmox vm's for clients, and that panel works fine. Blesta is also the only thing using user "apiuser@pve" and the cluster log on proxmox says that the user successfully authenticates with the given credentials

**Comment by joeymk2000** [comment]
setting default template to "default" instead of the iso name does work somehow. Thanks for the fast response!
